'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Brain, 
  CheckCircle, 
  XCircle, 
  RotateCcw, 
  Trophy, 
  Play,
  Loader2,
  AlertCircle
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';

/**
 * Module Quiz Section Component
 * 
 * Displays and handles quiz questions generated by Gemini AI
 * for individual course modules/chapters
 */
export default function ModuleQuizSection({ 
  moduleId, 
  moduleTitle, 
  quizData = [], 
  onScoreUpdate 
}) {
  // Quiz state
  const [isStarted, setIsStarted] = useState(false);
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [userAnswers, setUserAnswers] = useState({});
  const [showResults, setShowResults] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  // Results state
  const [score, setScore] = useState(0);
  const [correctCount, setCorrectCount] = useState(0);

  // If no quiz data, don't render anything
  if (!quizData || quizData.length === 0) {
    return null;
  }

  const totalQuestions = quizData.length;
  const currentQuestion = quizData[currentQuestionIndex];
  const progress = ((currentQuestionIndex + 1) / totalQuestions) * 100;
  const allQuestionsAnswered = quizData.every((_, index) => userAnswers[index] !== undefined);

  const startQuiz = () => {
    setIsStarted(true);
    setCurrentQuestionIndex(0);
    setUserAnswers({});
    setShowResults(false);
  };

  const handleAnswerSelect = (questionIndex, selectedOption) => {
    setUserAnswers(prev => ({
      ...prev,
      [questionIndex]: selectedOption
    }));
  };

  const nextQuestion = () => {
    if (currentQuestionIndex < totalQuestions - 1) {
      setCurrentQuestionIndex(prev => prev + 1);
    }
  };

  const previousQuestion = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(prev => prev - 1);
    }
  };

  const submitQuiz = async () => {
    setIsSubmitting(true);

    try {
      // Calculate score
      let correct = 0;
      quizData.forEach((question, index) => {
        if (userAnswers[index] === question.correct_answer) {
          correct++;
        }
      });

      const scorePercentage = Math.round((correct / totalQuestions) * 100);

      setCorrectCount(correct);
      setScore(scorePercentage);
      setShowResults(true);

      // Notify parent component
      if (onScoreUpdate) {
        onScoreUpdate(scorePercentage, correct, totalQuestions);
      }

      console.log(`Module ${moduleTitle} quiz completed:`, { 
        score: scorePercentage, 
        correct, 
        total: totalQuestions 
      });

    } catch (err) {
      console.error('Error submitting quiz:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const retakeQuiz = () => {
    setIsStarted(false);
    setShowResults(false);
    setUserAnswers({});
    setCurrentQuestionIndex(0);
    setScore(0);
    setCorrectCount(0);
  };

  const getScoreColor = (score) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 60) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getScoreMessage = (score) => {
    if (score >= 90) return 'Excellent! You have mastered this module! 🎉';
    if (score >= 80) return 'Great job! You understand the concepts well! 👏';
    if (score >= 70) return 'Good work! You grasp most of the material! 👍';
    if (score >= 60) return 'Not bad! Review the content and try again! 📚';
    return 'Keep studying! Review this module carefully! 💪';
  };

  return (
    <div className="w-full space-y-4">
      {/* Quiz Header */}
      <Card className="border-2 border-purple-200 bg-gradient-to-r from-purple-50 to-blue-50">
        <CardHeader className="pb-3">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-purple-600 rounded-full flex items-center justify-center">
                <Brain className="w-5 h-5 text-white" />
              </div>
              <div>
                <CardTitle className="text-lg text-purple-900">
                  Module Quiz
                </CardTitle>
                <p className="text-purple-700 text-sm">
                  Test your understanding of {moduleTitle}
                </p>
              </div>
            </div>
            <div className="text-sm text-purple-600 font-medium">
              {totalQuestions} Questions
            </div>
          </div>
        </CardHeader>
      </Card>

      {/* Quiz Content */}
      <AnimatePresence mode="wait">
        {!isStarted && !showResults && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
          >
            <Card>
              <CardContent className="py-8 text-center space-y-4">
                <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto">
                  <Play className="w-8 h-8 text-purple-600" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900 mb-2">Ready to Test Your Knowledge?</h3>
                  <p className="text-gray-600 max-w-md mx-auto">
                    This quiz contains {totalQuestions} questions about {moduleTitle}. 
                    Test your understanding of the key concepts covered in this module.
                  </p>
                </div>
                <Button onClick={startQuiz} size="lg" className="bg-purple-600 hover:bg-purple-700">
                  Start Quiz
                </Button>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {isStarted && !showResults && (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="space-y-4"
          >
            {/* Progress */}
            <Card>
              <CardContent className="py-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium text-gray-700">
                    Question {currentQuestionIndex + 1} of {totalQuestions}
                  </span>
                  <span className="text-sm text-gray-500">{Math.round(progress)}% Complete</span>
                </div>
                <Progress value={progress} className="h-2" />
              </CardContent>
            </Card>

            {/* Current Question */}
            <Card>
              <CardContent className="py-6">
                <div className="space-y-6">
                  <div>
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">
                      {currentQuestion.question}
                    </h3>
                  </div>

                  <div className="space-y-3">
                    {currentQuestion.options.map((option, index) => (
                      <label
                        key={index}
                        className={`flex items-center p-4 border-2 rounded-lg cursor-pointer transition-all hover:bg-gray-50 ${
                          userAnswers[currentQuestionIndex] === option
                            ? 'border-purple-500 bg-purple-50'
                            : 'border-gray-200'
                        }`}
                      >
                        <input
                          type="radio"
                          name={`question-${currentQuestionIndex}`}
                          value={option}
                          checked={userAnswers[currentQuestionIndex] === option}
                          onChange={() => handleAnswerSelect(currentQuestionIndex, option)}
                          className="w-4 h-4 text-purple-600 mr-4"
                        />
                        <span className="text-gray-800">{option}</span>
                      </label>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Navigation */}
            <Card>
              <CardContent className="py-3">
                <div className="flex items-center justify-between">
                  <Button
                    onClick={previousQuestion}
                    disabled={currentQuestionIndex === 0}
                    variant="outline"
                  >
                    Previous
                  </Button>

                  <div className="flex gap-2">
                    {currentQuestionIndex < totalQuestions - 1 ? (
                      <Button
                        onClick={nextQuestion}
                        disabled={!userAnswers[currentQuestionIndex]}
                        className="bg-purple-600 hover:bg-purple-700"
                      >
                        Next Question
                      </Button>
                    ) : (
                      <Button
                        onClick={submitQuiz}
                        disabled={!allQuestionsAnswered || isSubmitting}
                        className="bg-green-600 hover:bg-green-700"
                      >
                        {isSubmitting ? (
                          <>
                            <Loader2 className="w-4 h-4 animate-spin mr-2" />
                            Submitting...
                          </>
                        ) : (
                          'Submit Quiz'
                        )}
                      </Button>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        )}

        {showResults && (
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.95 }}
            className="space-y-4"
          >
            {/* Score Summary */}
            <Card className="border-2 border-green-200 bg-gradient-to-r from-green-50 to-blue-50">
              <CardContent className="py-6 text-center">
                <div className="space-y-4">
                  <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto">
                    <Trophy className="w-8 h-8 text-green-600" />
                  </div>
                  <div>
                    <h3 className="text-2xl font-bold text-gray-900 mb-2">Quiz Complete!</h3>
                    <p className="text-gray-600">{getScoreMessage(score)}</p>
                  </div>
                  <div className="flex items-center justify-center gap-6 text-lg">
                    <div className="text-center">
                      <div className={`text-2xl font-bold ${getScoreColor(score)}`}>{score}%</div>
                      <div className="text-sm text-gray-500">Score</div>
                    </div>
                    <div className="text-center">
                      <div className="text-2xl font-bold text-gray-900">{correctCount}/{totalQuestions}</div>
                      <div className="text-sm text-gray-500">Correct</div>
                    </div>
                  </div>
                  <Button onClick={retakeQuiz} variant="outline">
                    <RotateCcw className="w-4 h-4 mr-2" />
                    Retake Quiz
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Detailed Results */}
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Review Answers</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {quizData.map((question, index) => {
                  const userAnswer = userAnswers[index];
                  const isCorrect = userAnswer === question.correct_answer;
                  
                  return (
                    <div key={index} className="border rounded-lg p-4">
                      <div className="flex items-start gap-3 mb-3">
                        {isCorrect ? (
                          <CheckCircle className="w-5 h-5 text-green-500 mt-1 flex-shrink-0" />
                        ) : (
                          <XCircle className="w-5 h-5 text-red-500 mt-1 flex-shrink-0" />
                        )}
                        <div className="flex-1">
                          <h4 className="font-medium text-gray-900 mb-2">
                            Question {index + 1}: {question.question}
                          </h4>
                          <div className="space-y-2 text-sm">
                            <div className={`p-2 rounded ${isCorrect ? 'bg-green-50 text-green-800' : 'bg-red-50 text-red-800'}`}>
                              <strong>Your answer:</strong> {userAnswer || 'Not answered'}
                            </div>
                            {!isCorrect && (
                              <div className="p-2 bg-green-50 text-green-800 rounded">
                                <strong>Correct answer:</strong> {question.correct_answer}
                              </div>
                            )}
                            {question.explanation && (
                              <div className="p-2 bg-blue-50 text-blue-800 rounded">
                                <strong>Explanation:</strong> {question.explanation}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
